#!/usr/bin/env bash
# Stop the currently running Nginx process
service nginx stop

# Update the nginx.conf file to run Nginx as the nginx user
sed -i 's/user\s*nginx;/user root;/g' /etc/nginx/nginx.conf

service nginx start
