#!/usr/bin/env bash

# Update the package index and install Nginx
sudo apt update
sudo apt install nginx -y

sudo vi /etc/nginx/sites-available/default

cat <<EOL | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    # Add the X-Served-By header here
    add_header X-Served-By \$hostname;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files \$uri \$uri/ =404;
    }
}
EOL

sudo nginx -t

sudo service nginx reload
