#!/usr/bin/env bash
#config nginx
sudo apt remove --purge nginx nginx-full nginx-common -y
sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html

echo "Holberton School" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

printf %b 'server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html;
        error_page 404 /custom_404.html;

        server_name _;

        add_header X-Served-By $hostname;

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
}
' | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
