#!/usr/bin/env bash

#webserver nginx config
sudo apt update
sudo apt install nginx -y

# Create a backup of the original configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Replace the configuration using sed
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/# Add the X-Served-By header here/add_header X-Served-By $hostname;/g' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload
