#!/usr/bin/env bash
#configure Nginx with a custom 404 page 'Ceci n'est pas une page'
sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
sudo touch /var/www/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo tee /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    error_page 404 /custom_404.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
